"use client"

import { useEffect, useState } from "react"
import Image from "next/image"
import { CalendarPlus, Check, Clock3, Copy, Gift, MapPin, MessageCircle, Music2 } from "lucide-react"
import type { InvitationDraft } from "./invitation-editor"
import type { InvitationTemplate } from "@/lib/invita"

export function PublishedInvitation({ template }: { template: InvitationTemplate }) {
  const [draft, setDraft] = useState<InvitationDraft>({ hosts: template.hosts, date: template.date, location: template.location, color: template.color, music: true })
  const [name, setName] = useState("")
  const [guests, setGuests] = useState("1")
  const [error, setError] = useState("")
  const [confirmed, setConfirmed] = useState(false)
  const [copied, setCopied] = useState(false)

  useEffect(() => { try { const saved = localStorage.getItem(`invita-draft-${template.slug}`); if (saved) setDraft(JSON.parse(saved)) } catch {} }, [template.slug])
  const shareUrl = typeof window === "undefined" ? "" : window.location.href
  const submit = (event: React.FormEvent) => { event.preventDefault(); if (name.trim().length < 2) { setError("Escribe tu nombre para confirmar."); return } setError(""); setConfirmed(true) }
  const copy = async () => { await navigator.clipboard.writeText(shareUrl); setCopied(true); setTimeout(()=>setCopied(false),2000) }

  return (
    <main className="bg-[#f8f4ed] text-[#211f1c]">
      <section className="relative min-h-[100svh]"><Image src={template.image} alt={`Celebración de ${draft.hosts}`} fill priority sizes="100vw" className="object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-black/85 via-black/15 to-black/25"/><div className="absolute inset-x-0 bottom-0 mx-auto max-w-5xl px-6 pb-16 text-center text-white"><p className="text-xs uppercase tracking-[.35em]">{template.event}</p><h1 className="mt-5 font-serif text-6xl leading-[.88] md:text-9xl">{draft.hosts}</h1><p className="mt-7 text-sm tracking-[.22em]">{draft.date}</p><p className="mt-3 text-sm text-white/70">{draft.location}</p></div>{draft.music && <button type="button" className="absolute right-5 top-5 grid size-11 place-items-center rounded-full border border-white/30 bg-black/15 text-white backdrop-blur" aria-label="Reproducir música"><Music2 className="size-4"/></button>}</section>
      <section className="px-6 py-24 text-center"><p className="eyebrow">Faltan</p><div className="mx-auto mt-10 grid max-w-3xl grid-cols-4 gap-3">{[["64","días"],["08","horas"],["32","min"],["18","seg"]].map(([n,label])=><div key={label} className="rounded-2xl border border-black/10 bg-white p-4"><strong className="block font-serif text-3xl md:text-5xl">{n}</strong><span className="mt-1 block text-[10px] uppercase tracking-[.15em] text-muted-foreground">{label}</span></div>)}</div></section>
      <section className="bg-[#211f1c] px-6 py-24 text-white"><div className="mx-auto max-w-5xl text-center"><p className="eyebrow text-white/50">El gran día</p><h2 className="mt-5 font-serif text-5xl md:text-7xl">Celebremos juntos</h2><div className="mt-14 grid gap-4 text-left md:grid-cols-3">{[[CalendarPlus,"Fecha",draft.date],[Clock3,"Hora","16:30 h"],[MapPin,"Lugar",draft.location]].map(([Icon,title,text])=><div key={title as string} className="rounded-3xl border border-white/15 p-6"><Icon className="size-5"/><p className="mt-12 text-xs uppercase tracking-[.18em] text-white/45">{title as string}</p><p className="mt-2 text-sm">{text as string}</p></div>)}</div><a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(draft.location)}`} target="_blank" rel="noreferrer" className="mt-8 inline-flex rounded-full bg-white px-6 py-3 text-sm text-black">Abrir ubicación</a></div></section>
      <section className="px-4 py-20 md:px-6"><div className="mx-auto grid max-w-6xl auto-rows-[230px] grid-cols-2 gap-3 md:grid-cols-4">{["photo-1511285560929-80b456fea0bc","photo-1520854221256-17451cc331bf","photo-1507501336603-6e31db2be093","photo-1464366400600-7168b8af9bc3"].map((photo,i)=><div key={photo} className={`relative overflow-hidden rounded-3xl ${i===0?"col-span-2 row-span-2":i===3?"col-span-2":""}`}><Image src={`https://images.unsplash.com/${photo}?auto=format&fit=crop&w=1000&q=80`} alt="Momento de la celebración" fill sizes="50vw" className="object-cover"/></div>)}</div></section>
      <section className="bg-[#ded8ce] px-6 py-24"><div className="mx-auto grid max-w-5xl gap-12 md:grid-cols-2 md:items-center"><div><p className="eyebrow">Confirma tu asistencia</p><h2 className="mt-5 font-serif text-5xl leading-none md:text-7xl">Queremos celebrar contigo.</h2><div className="mt-8 flex gap-2"><a href={`https://wa.me/?text=${encodeURIComponent(`Acompáñanos a celebrar ${draft.hosts}: ${shareUrl}`)}`} target="_blank" rel="noreferrer" className="grid size-11 place-items-center rounded-full border border-black/15" aria-label="Compartir por WhatsApp"><MessageCircle className="size-4"/></a><button type="button" onClick={copy} className="inline-flex items-center gap-2 rounded-full border border-black/15 px-4 text-xs"><Copy className="size-4"/>{copied?"Enlace copiado":"Copiar enlace"}</button></div></div>{confirmed?<div className="rounded-[2rem] bg-[#fffdf8] p-10 text-center" role="status"><Check className="mx-auto size-10 text-primary"/><h3 className="mt-5 font-serif text-4xl">¡Nos vemos ahí!</h3><p className="mt-3 text-sm text-muted-foreground">Registramos tu asistencia para {guests} {guests === "1" ? "persona" : "personas"}.</p></div>:<form onSubmit={submit} noValidate className="rounded-[2rem] bg-[#fffdf8] p-7"><label className="block text-xs font-semibold">Nombre completo<input value={name} onChange={(e)=>setName(e.target.value)} className="mt-2 w-full rounded-xl border border-black/10 px-4 py-3 text-sm outline-none focus:ring-2 focus:ring-primary" aria-invalid={!!error}/></label>{error&&<p className="mt-2 text-xs text-destructive" role="alert">{error}</p>}<label className="mt-5 block text-xs font-semibold">Número de asistentes<select value={guests} onChange={(e)=>setGuests(e.target.value)} className="mt-2 w-full rounded-xl border border-black/10 bg-white px-4 py-3 text-sm"><option>1</option><option>2</option><option>3</option><option>4</option></select></label><label className="mt-5 block text-xs font-semibold">Mensaje para los anfitriones<textarea className="mt-2 min-h-24 w-full rounded-xl border border-black/10 px-4 py-3 text-sm" placeholder="Opcional"/></label><button className="mt-5 w-full rounded-full bg-foreground px-5 py-3.5 text-sm text-background">Confirmar asistencia</button></form>}</div></section>
      <section className="px-6 py-20 text-center"><Gift className="mx-auto size-6 text-primary"/><h2 className="mt-5 font-serif text-4xl">Tu presencia es nuestro mejor regalo</h2><p className="mx-auto mt-4 max-w-md text-sm leading-6 text-muted-foreground">Si deseas tener un detalle con nosotros, consulta aquí nuestra mesa de regalos.</p></section>
    </main>
  )
}
